### ISSUE TITLE
Authorization failed occurs with Enter-PSSession

### ISSUE THREAD

**Issue by nico2610** [quickbreach/PowerShell-NTLM#1]
I'm trying to connect remotly a windows server from a linux following your blog article https://blog.quickbreach.io/ps-remote-from-linux-to-windows/

here is my config : 

* Source is in container from `quickbreach/powershell-ntlm` docker image deployed in kubernetes, not in a domain (powershell version 6.1.1)
* destination is a Windows Server 2016 in a domain (powershell version 5.1)

I executed all steps of the article with success except the  `Enter-PSSession` where I got an Authorization failed : 

```
PS /> Enter-PSSession -ComputerName 1.2..3.4 -Authentication Negotiate -Credential $creds
Enter-PSSession : Connecting to remote server 1.2.3.4 failed with the following error message : Authorization failed For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Enter-PSSession -ComputerName 1.2.3.4 -Authent ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (1.2.3.4:String) [Enter-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : CreateRemoteRunspaceFailed
```

I don't know what's different from your example. Maybe I because of the domain ? Or the different poweshell version ?

**Comment by nico2610** [comment]
my users didn't the sufficient right in powershell to execute ps remote. I fixed it executing `Set-PSSessionConfiguration -ShowSecurityDescriptorUI -Name Microsoft.PowerShell` (run-as in administrator) and giving the correct rights. Sorry for the non-sense issue.

**Comment by vinaykumar-rm** [comment]
i am trying to run script `Set-PSSessionConfiguration -ShowSecurityDescriptorUI -Name Microsoft.PowerShell` but getting below error

Set-PSSessionConfiguration : The term 'Set-PSSessionConfiguration' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Set-PSSessionConfiguration -ShowSecurityDescriptorUI -Name Microsoft. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Set-PSSessionConfiguration:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
